services:
  database:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  adminer:
    image: adminer
    restart: always
    environment: 
      ADMINER_DESIGN: hydra # tema do adminer
    depends_on:
      - database
    ports:
      - 8080:8080
    volumes:
      - ./assets/adminer.css:/var/www/html/designs/hydra/adminer.css # asset dari tema hydra komentari jika tidak menggunakan tema hydra